# Jazzy config
module:      OAuth2

author_url:  http://www.github.com/p2
root_url:    http://smart-on-fhir.github.io/Swift-SMART
github_url:  http://p2.github.io/OAuth2

theme:       fullwidth
readme:      README.md
